config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  mount Linkus::API => '/api'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'users#index'
  resources :users

  namespace :admin do
    resources :users, except: [:new, :create] do
      post :lock, on: :member
      post :unlock, on: :member
    end
  end
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ActiveRecord::Base
  has_many :group_users
  has_many :users, through: :group_users

  validates_uniqueness_of :name
end

app/models/group_user.rb
# == Schema Information
#
# Table name: group_users
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  group_id   :integer
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  POSITION = %w(なし リーダー サブリーダー).freeze

  module Select
    POSITION = POSITION.map.with_index { |pos, i| [pos, i] }
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string           default(""), not null
#  encrypted_password  :string           default(""), not null
#  remember_created_at :datetime
#  sign_in_count       :integer          default(0), not null
#  current_sign_in_at  :datetime
#  last_sign_in_at     :datetime
#  current_sign_in_ip  :inet
#  last_sign_in_ip     :inet
#  failed_attempts     :integer          default(0), not null
#  unlock_token        :string
#  locked_at           :datetime
#  sid                 :string           not null
#  name                :string
#  laboratory          :integer          default(0), not null
#  position            :integer          default(0), not null
#  phone               :string           default(""), not null
#  address             :string
#  birthday            :date
#  role                :integer          default(0), not null
#  status              :integer          default(0), not null
#  provider            :string
#  uid                 :string
#  token               :string
#  raw                 :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :lockable, :omniauthable

  has_many :group_users
  has_many :groups, through: :group_users

  before_save :update_sid!
  before_save :check_status!

  accepts_nested_attributes_for :group_users, reject_if: :all_blank, allow_destroy: true

  validates_uniqueness_of :email

  LABORATORY = %w(無所属 富永研 林研 八重樫研 垂水研 安藤研 最所研 その他).freeze
  POSITION = %w(なし 会計 所長 副所長 会計 広報 物品 旅行 事務).freeze

  module Select
    ROLE = [['管理者', 100], ['一般', 0]]
    LABORATORY = LABORATORY.map.with_index { |labo, i| [labo, i] }
    POSITION = POSITION.map.with_index { |pos, i| [pos, i] }
  end

  def schema
    {
      uid: uid,
      sid: sid,
      name: name
    }
  end

  def self.find_for_google_oauth2(auth)
    return false unless check_email(auth.info.email)
    user = User.where(email: auth.info.email).first
    return update_google!(user, auth) if user

    User.create(
      name:     auth.info.name,
      provider: auth.provider,
      uid:      auth.uid,
      email:    auth.info.email,
      token:    auth.credentials.token,
      password: Devise.friendly_token[0, 20],
      raw: auth.to_json
    )
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    params.delete(:password) if params[:password].blank?
    params.delete(:password_confirmation) if params[:password_confirmation].blank?

    clean_up_passwords
    update_attributes(params, *options)
  end

  def self.update_google!(user, auth)
    user.update(
      name:     auth.info.name,
      provider: auth.provider,
      uid:      auth.uid,
      email:    auth.info.email,
      token:    auth.credentials.token,
      password: Devise.friendly_token[0, 20],
      raw: auth.to_json
    )
    user
  end

  def is_admin?
    100 <= role
  end

  def is_verified?
    100 <= status
  end

  def update_sid!
    self.sid = email.split('@').first
  end

  def check_status!
    flag = true
    skip_columns = %w(
      id
      encrypted_password
      reset_password_token
      reset_password_sent_at
      remember_created_at
      sign_in_count
      current_sign_in_at
      last_sign_in_at
      current_sign_in_ip
      last_sign_in_ip
      failed_attempts
      unlock_token
      locked_at
      role
      status
      created_at
      updated_at
    )
    self.class.columns.each do |col|
      target = col.name
      next if skip_columns.include?(target)
      flag = false unless try(target).present?
    end
    self.status = flag ? 100 : 0
  end

  def self.check_email(email)
    return true if WhiteList.where(active: true).pluck(:email).index(email)
    return false unless email.split('@')[1].include?('kagawa-u.ac.jp')
    true
  end
end

app/models/white_list.rb
# == Schema Information
#
# Table name: white_lists
#
#  id         :integer          not null, primary key
#  email      :string           not null
#  active     :boolean          default(TRUE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class WhiteList < ActiveRecord::Base
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :load_user, except: [:index, :new, :create]

  def index
    @search = User.search(params[:q])
    @users = @search.result.page(params[:page]).per(20)
  end

  def edit
    render :show_modal_form
  end

  def update
    @user.update_without_current_password(user_params)
    render :reload
  end

  def destroy
    @user.destroy
    render :reload
  end

  def lock
    @user.lock_access!
    render :reload
  end

  def unlock
    @user.unlock_access!
    render :reload
  end

  private

  def user_params
    params.require(:user).permit(
      :birthday, :role, :laboratory, :position, :phone, :address,
      group_users_attributes: [:id, :group_id, :position, :_destroy]
    )
  end

  def load_user
    return unless params[:id]
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def admin_user!
    return if current_user.is_admin?
    redirect_to root_path, alert: '管理者用ページです'
  end

  def verified_user!
    return if current_user.is_verified? || current_user.is_admin?
    sign_out
    redirect_to root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.find_for_google_oauth2(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      if session[:return_to]
        sign_in @user
        redirect_to session[:return_to]
        session[:return_to] = nil
      else
        sign_in_and_redirect @user, event: :authentication
      end
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_session_url, alert: @user.errors
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :verified_user!

  def index
    @search = User.ransack(params[:q])
    @users = @search.result.page(params[:page]).per(20)
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.slim
- unless user
  - user = User.new
  - title = 'ユーザの新規作成'
  - submit = '作成'
- else
  - title = 'ユーザの更新'
  - submit = '更新'

.uk-modal-dialog style="padding-bottom: 0"
  a.uk-modal-close.uk-close

  = form_for [:admin, user], html: { class: 'uk-form uk-form-stacked' }, remote: true do |f|
    .uk-modal-header
      h4.bold
        = fa_icon 'user', text: title

    .uk-form-row
      .uk-form-icon
        i.uk-icon-envelope
        = f.text_field :email, autofocus: true, placeholder: 'メールアドレス', style: 'padding-left: 30px;', disabled: true
      .uk-form-help-block#user-email-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-font
        = f.text_field :name, placeholder: '名前', style: 'padding-left: 30px;', disabled: true
      .uk-form-help-block#user-name-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-phone
        = f.text_field :phone, placeholder: '電話番号', style: 'padding-left: 30px;'
      .uk-form-help-block#user-phone-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-home
        = f.text_field :address, placeholder: '住所', style: 'padding-left: 30px;'
      .uk-form-help-block#user-address-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-birthday-cake
        = f.text_field :birthday, placeholder: '誕生日', class: 'uk-width-1-1', "data-uk-datepicker" => "{format: 'YYYY-MM-DD'}", readonly: true
      .uk-form-help-block#user-birthday-error
    .uk-form-row
      = f.select :laboratory, User::Select::LABORATORY, {}, { class: 'uk-width-1-1 select2-form' }
    .uk-form-row
      = f.select :position, User::Select::POSITION, {}, { class: 'uk-width-1-1 select2-form' }
    .uk-form-row
      = f.select :role, User::Select::ROLE, {}, { class: 'uk-width-1-1 select2-form' }
    .uk-form-row
      = f.fields_for :group_users do |gu|
        = render partial: 'group_user_fields', locals: { f: gu }
      .
        = link_to_add_association f, :group_users, class: 'uk-button uk-button-success uk-button-mini'
          = fa_icon 'plus', text: '追加'

    .uk-modal-footer.uk-text-right
      .uk-button-group
        button.uk-button.uk-button-primary
          = fa_icon 'floppy-o', text: submit
        button.uk-button.uk-modal-close
          = fa_icon 'times', text: 'キャンセル'

coffee:
  $('.select2-form').select2()
  $('form').on 'cocoon:after-insert', ->
    $('select.select2-form').select2()

app/views/admin/users/_list.html.slim
.uk-overflow-container
  table.uk-table.uk-table-striped
    thead
      tr
        th style="width: 150px;"
        th.bold.uk-text-center style="width: 100px;" = sort_link(@search, :sid, '学籍番号')
        th.bold.uk-text-center style="width: 50px;" = sort_link(@search, :role, '管理者')
        th.bold.uk-text-center style="width: 50px;" = sort_link(@search, :status, '承認')
        th.bold.uk-text-center style="width: 150px;" = sort_link(@search, :name, '名前')
        th.bold.uk-text-center style="width: 150px;" = sort_link(@search, :group, 'チーム')
        th.bold.uk-text-center style="width: 50px;" = sort_link(@search, :laboratory, '研究室')
        th.bold.uk-text-center style="width: 100px;" = sort_link(@search, :position, '役職')
        th.bold.uk-text-center style="width: 150px;" = sort_link(@search, :last_sign_in_at, '最終ログイン時間')
    tbody
      - users.each do |user|
        - user = user.decorate
        tr
          td
            - unless user.access_locked?
              = link_to edit_admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-success uk-margin-small-right', remote: true
                = fa_icon 'pencil', text: '編集'
              = link_to lock_admin_user_path(user.id), class: 'uk-button uk-button-mini', method: :post, remote: true
                = fa_icon 'lock', text: '無効化'
            - else
              = link_to unlock_admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-primary uk-margin-small-right', method: :post, remote: true
                = fa_icon 'level-up', text: '有効化'
              = link_to admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-danger', method: :delete, remote: true
                = fa_icon 'trash', text: '削除'

          td.uk-text-center = user.sid
          td.uk-text-center = fa_icon 'check' if user.is_admin?
          td.uk-text-center = fa_icon 'check' if user.is_verified?
          td.uk-text-center = user.name
          td.uk-text-center = user.group_users.includes(:group).map { |gu| gu.decorate.name_and_position }.join(',')
          td.uk-text-center = user.laboratory
          td.uk-text-center = user.position
          td.uk-text-center = user.last_sign_in_at
coffee:
  $('.select2').select2()

app/views/admin/users/index.html.slim
- @title = 'ユーザー'

h2.bold
  = fa_stacked_icon 'users inverse', base: 'square', text: @title

= search_form_for [:admin, @search], class: 'uk-form right' do |f|
  = fa_icon 'search', text: '学籍番号から絞込'
  .uk-form-row
    = f.select :id_eq, User.all.map { |u| [u.sid, u.id] }, {}, class: 'select2', style: 'width: 100px'
    button.uk-button.uk-button-primary onClick="$('.uk-panel > .uk-form').submit()"
      = fa_icon 'search', text: '検索'
hr
= render partial: 'admin/users/list', locals: { users: @users }
= paginate @users

coffee:
  $('#nav-admin').addClass('uk-active')

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{@title} | linkus
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag

  body
    .loading-container = image_tag('loading.gif')
    .uk-modal

    nav.uk-navbar.uk-navbar-attached
      .uk-container.uk-container-center
        = link_to root_path, class: 'uk-navbar-brand'
          span.brand.bold
            = fa_icon 'connectdevelop', text: 'linkus'

        - if user_signed_in?
          ul.uk-navbar-nav.uk-hidden-small
            li = link_to '利用者一覧', root_path

        .uk-navbar-flip.uk-hidden-small
          ul.uk-navbar-nav
            - if user_signed_in?
              - if current_user.is_admin?
                li.uk-parent data-uk-dropdown=""
                  a = fa_icon 'gears', text: '管理'
                  .uk-dropdown.uk-dropdown-navbar
                    ul.uk-nav.uk-nav-navbar
                      li
                        = link_to admin_users_path
                          = fa_icon 'users', text: 'ユーザ管理'
              li.uk-parent data-uk-dropdown=""
                a = fa_icon 'user', text: current_user.sid
                .uk-dropdown.uk-dropdown-navbar
                  ul.uk-nav.uk-nav-navbar
                    li
                      = link_to edit_user_path(current_user.id)
                        = fa_icon 'pencil fw', text: '編集'
                      = link_to destroy_user_session_path, method: :delete
                        = fa_icon 'sign-out fw', text: 'ログアウト'

            - else
              li
                = link_to new_user_session_path
                  = fa_icon 'sign-in', text: 'ログイン'

        .uk-navbar-flip.uk-visible-small
          a.uk-navbar-toggle href="#navbar-offcanvas" data-uk-offcanvas=""

    .uk-offcanvas#navbar-offcanvas
      .uk-offcanvas-bar.uk-offcanvas-bar-flip
        ul.uk-nav.uk-nav-offcanvas.uk-nav-parent-icon data-uk-nav=""
          - if user_signed_in?
            - if current_user.is_admin?
              li.uk-nav-header = fa_icon 'gears', text: '管理'
              li
                = link_to admin_users_path
                  = fa_icon 'users', text: 'ユーザ管理'
              li.uk-nav-header = fa_icon 'user fw', text: current_user.sid
              li
                = link_to destroy_user_session_path, method: :delete
                  = fa_icon 'sign-out fw', text: 'ログアウト'
          - else
            li
              = link_to new_user_session_path
                = fa_icon 'sign-in fw', text: 'ログイン'

    .uk-container.uk-container-center.uk-margin-top.uk-margin-bottom
      = yield

    .uk-container.uk-container-center.uk-margin-bottom
      footer
        .relative
          .uk-panel.panel-default.center
            span &copy; linkus SLP-KBIT 2015
- if notice
  javascript:
    UIkit.notify({ message: '#{notice}', timeout: 3000 });

- if alert
  javascript:
    UIkit.notify({ message: '#{alert}', timeout: 3000, status: 'danger' });

app/views/users/_group_user_fields.html.slim
.nested-fields
  .uk-form-row
    = f.collection_select(:group_id, Group.all, :id, :name, {}, { class: 'uk-grid-1-2 select2-form' })
    = f.select :position, GroupUser::Select::POSITION, {}, { class: 'uk-width-1-2 select2-form' }
    = link_to_remove_association f, class: 'uk-button uk-button-danger uk-button-mini'
      = fa_icon 'remove', text: '削除'

app/views/users/_list.html.slim
.uk-overflow-container
  table.uk-table.uk-table-striped
    thead
      tr
        th.bold.uk-text-center style="width: 100px;" = sort_link(@search, :sid, '学籍番号')
        th.bold.uk-text-center style="width: 50px;" = sort_link(@search, :role, '管理者')
        th.bold.uk-text-center style="width: 50px;" = sort_link(@search, :status, '承認')
        th.bold.uk-text-center style="width: 150px;" = sort_link(@search, :name, '名前')
        th.bold.uk-text-center style="width: 150px;" = sort_link(@search, :group, 'チーム')
        th.bold.uk-text-center style="width: 50px;" = sort_link(@search, :laboratory, '研究室')
        th.bold.uk-text-center style="width: 100px;" = sort_link(@search, :position, '役職')
        th.bold.uk-text-center style="width: 150px;" = sort_link(@search, :last_sign_in_at, '最終ログイン時間')
    tbody
      - users.each do |user|
        - user = user.decorate
        tr
          td.uk-text-center = user.sid
          td.uk-text-center = fa_icon 'check' if user.is_admin?
          td.uk-text-center = fa_icon 'check' if user.is_verified?
          td.uk-text-center = user.name
          td.uk-text-center = user.group_users.includes(:group).map { |gu| gu.decorate.name_and_position }.join(',')
          td.uk-text-center = user.laboratory
          td.uk-text-center = user.position
          td.uk-text-center = user.last_sign_in_at
coffee:
  $('.select2').select2()

app/views/users/edit.html.slim
- title = 'ユーザの更新'
- submit = '更新'
h4.bold
  = fa_icon 'user', text: title

= form_for current_user, html: { class: 'uk-form uk-form-stacked' }, remote: true do |f|

  .uk-form-row
    .uk-form-icon
      i.uk-icon-envelope
      = f.text_field :email, autofocus: true, placeholder: 'メールアドレス', style: 'padding-left: 30px;', disabled: true
    .uk-form-help-block#user-email-error
  .uk-form-row
    .uk-form-icon
      i.uk-icon-font
      = f.text_field :name, placeholder: '名前', style: 'padding-left: 30px;', disabled: true
    .uk-form-help-block#user-name-error
  .uk-form-row
    .uk-form-icon
      i.uk-icon-phone
      = f.text_field :phone, placeholder: '電話番号', style: 'padding-left: 30px;'
    .uk-form-help-block#user-phone-error
  .uk-form-row
    .uk-form-icon
      i.uk-icon-home
      = f.text_field :address, placeholder: '住所', style: 'padding-left: 30px;'
    .uk-form-help-block#user-address-error
  .uk-form-row
    .uk-form-icon
      i.uk-icon-birthday-cake
      = f.text_field :birthday, placeholder: '誕生日', class: 'uk-width-1-1', "data-uk-datepicker" => "{format: 'YYYY-MM-DD'}", readonly: true
    .uk-form-help-block#user-birthday-error
  .uk-form-row
    = f.select :laboratory, User::Select::LABORATORY, {}, { class: 'uk-width-1-1 select2-form' }
  .uk-form-row
    = f.select :position, User::Select::POSITION, {}, { class: 'uk-width-1-1 select2-form' }
  .uk-form-row
    = f.select :role, User::Select::ROLE, {}, { class: 'uk-width-1-1 select2-form' }
  .uk-form-row
    = f.fields_for :group_users do |gu|
      = render partial: 'group_user_fields', locals: { f: gu }
    .
      = link_to_add_association f, :group_users, class: 'uk-button uk-button-success uk-button-mini'
        = fa_icon 'plus', text: '追加'
  .uk-button-group
    button.uk-button.uk-button-primary
      = fa_icon 'floppy-o', text: submit
    button.uk-button.uk-modal-close
      = fa_icon 'times', text: 'キャンセル'

coffee:
  $('.select2-form').select2()
  $('form').on 'cocoon:after-insert', ->
    $('select.select2-form').select2()

app/views/users/index.html.slim
- @title = '利用者一覧'

h2.bold
  = fa_stacked_icon 'users inverse', base: 'square', text: @title

= search_form_for @search, class: 'uk-form right' do |f|
  = fa_icon 'search', text: '学籍番号から絞込'
  .uk-form-row
    = f.select :id_eq, User.all.map { |u| [u.sid, u.id] }, {}, class: 'select2', style: 'width: 100px'
    button.uk-button.uk-button-primary onClick="$('.uk-panel > .uk-form').submit()"
      = fa_icon 'search', text: '検索'
hr
= render partial: 'users/list', locals: { users: @users }
= paginate @users

coffee:
  $('#nav-admin').addClass('uk-active')